version: "3"

vars:
  WORKSPACE_DIR: "${HOME}/workspace/xcaliapp"
  WEBCLIENT_DIST: '{{ .WEBCLIENT_DIST | default "../webclient/dist" }}'

tasks:
  test:
    cmds:
      - go test -parallel 1 -v -timeout 60s ./...
  plain:
    cmds:
      - |
        go build -o xcaliapp-backend
  with-webclient:
    cmds:
      - |
        GOOS=${GOOS:-linux}
        GOARCH=${GOARCH:-amd64}

        mkdir -p ./webclient_dist
        cp -a {{.WEBCLIENT_DIST}}/* webclient_dist/
        output_file="xcaliapp_${GOOS}_${GOARCH}"
        go build -o $output_file
  run:
    cmds:
      - task: plain
      - |
        ./xcaliapp-backend
