version: "3"

vars:
  WORKSPACE_DIR: "${HOME}/workspace/xcaliapp"
  WEBCLIENT_DIST: '{{ .WEBCLIENT_DIST | default "../webclient/dist" }}'

tasks:
  test:
    cmds:
      - go test -parallel 1 -v -timeout 60s ./...
  plain:
    cmds:
      - go build -o xcaliapp-backend
      - cmd: mv xcaliapp-backend xcaliapp-backend.exe
        platforms: [windows]

  with-webclient:
    cmds:
      - |
        GOOS=${GOOS:-linux}
        GOARCH=${GOARCH:-amd64}

        mkdir -p ./webclient_dist
        cp -a {{.WEBCLIENT_DIST}}/* webclient_dist/
        output_file="xcaliapp_${GOOS}_${GOARCH}"
        go build -o $output_file
  run:
    cmds:
      - task: plain
      - |
        LOG_LEVEL=debug \
          XCALIAPP_USERNAME="peter.dunay.kovacs@gmail.com" \
          SERVER_PORT=8888 \
          XCALIAPP_DRAWINGREPO_LIST="xcaliapp:XCalidraw Application,wsgw:WebSocket Gateway" \
          XCALIAPP_DRAWINGREPO_xcaliapp_STORETYPE=LOCAL_GIT \
          XCALIAPP_DRAWINGREPO_xcaliapp_ROOT=C:\Users\pkovacs\gitlab\diagrams\xcalidraw \
          XCALIAPP_DRAWINGREPO_xcaliapp_PATH=/ \
          XCALIAPP_DRAWINGREPO_wsgw_STORETYPE=LOCAL_GIT \
          XCALIAPP_DRAWINGREPO_wsgw_ROOT=C:\Users\pkovacs\github\pdkovacs\wsgw \
          XCALIAPP_DRAWINGREPO_wsgw_PATH=doc/design/diagrams \
          ./xcaliapp-backend
