version: "3"

vars:
  WORKSPACE_DIR: "${HOME}/workspace/xcaliapp"
  WEBCLIENT_DIST: '{{ .WEBCLIENT_DIST | default "../webclient/dist" }}'

tasks:
  plain:
    cmds:
      - |
        go build -o xcaliapp-backend
  with-webclient:
    cmds:
      - |
        mkdir -p ./webclient_dist
        cp -a {{.WEBCLIENT_DIST}}/* webclient_dist/
        output_file=xcaliapp
        if [ -n "$GOARCH" ];
        then
          output_file="${output_file}_${GOOS}_${GOARCH}"
        fi
        go build -o $output_file
  run:
    cmds:
      - task: plain
      - |
        ./xcaliapp-backend